var tableauQuestion = [
        {   question : "Dacă conduceți la 80 km h și vă apropiați de o zonă rezidențială, ar trebui să: ",
        propositionA : "Acelerez inainte",
        propositionB : "Accelerez atâat timp cat nu sunt mașini in preajma",
        propositionC : "Încetinesc",
        propositionD : "Îmi pot menține viteza",
        reponse : "C"},
		
        {   question : "În timp ce întoarceți la stânga pe verde, vedeți că un pieton se află pe trecere. Cine are prioritate?",
        propositionA : "Pietonul deoarece poate trece la orice culoare",
        propositionB : "Vehiculul tău deoarece este verde",
        propositionC : "Pietonul deorece trece pe culoarea verde",
        propositionD : "Vehiculul tău deoarece are mereu prioritate",
        reponse : "C"},
		
        {   question : "Cu excepția cazului în care este afișată, viteza maximă într-o zonă rezidențială este de ____ kmh",
        propositionA : "50",
        propositionB : "55",
        propositionC : "65",
        propositionD : "70",
        reponse : "A"},
	
	{   question : "Înainte de fiecare schimbare de bandă, ar trebui.",
        propositionA : "Să verific oglinzile",
        propositionB : "Să verific punctele moarte",
        propositionC : "Să semnalizez",
        propositionD : "Toate de sus",
        reponse : "D"},
		
	{   question : "Ce nivel de alcool din sânge este clasificat ca fiind condus în stare de ebrietate?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},
		
	{   question : "Trebuie să trag pe dreapta atunci când orice vehicul de urgență cu sirena trece, cu excepția cazului în care:",
        propositionA : "Ești in grabă",
        propositionB : "Nu este destul loc in banda de alături",
        propositionC : "Esti intr-o zona școalara",
        propositionD : "Te afli intr-o întersecție",
        reponse : "D"},
	
	{   question : "Drumul de trecere trebuie cedat vehiculelor de urgență",
        propositionA : "Mereu",
        propositionB : "Cand are girofarul aprins",
        propositionC : "Cand are girofarul si sirena aprinsa",
        propositionD : "Cand are sirene aprinsa",
        reponse : "C"},
		
	{   question : "Care dintre următoarele este permis atunci când întreci un alt vehicul?",
        propositionA : "Să urmarești din apropiere",
        propositionB : "Să îi spargi roțile ca sa nu mai mearga atât de repede",
        propositionC : "Să mergi pe partea opasa a drumului",
        propositionD : "Să întreci limita de viteză",
        reponse : "C"},
		
	{   question : "Conduci pe o autostradă cu o limită de viteză afișată de 110 kmh. Cea mai mare parte a traficului circulă cu o viteză de 120 kmh, deci ar trebui sa conduci cu: ",
        propositionA : "80 kmh",
        propositionB : "40 kmh",
        propositionC : "120 kmh",
        propositionD : "110 kmh",
        reponse : "D"},
		
	{   question : "Când ești întrecut de un alt vehicul, este important să NU",
        propositionA : "Încetinesc",
        propositionB : "Verific oglinzele",
        propositionC : "Bag manele si îi dau bataie",
        propositionD : "Mă îintrec cu el",
        reponse : "D"},
]
